-- liquibase formatted sql

-- changeset sergey_yakovlev:1
CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    email      VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255),
    phone      VARCHAR(20),
    role       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);
-- rollback drop table users;

-- changeset sergey_yakovlev:2
ALTER TABLE users
    ADD CONSTRAINT users_uq_email UNIQUE (email);
-- rollback alter table users drop constraint users_uq_email;

-- changeset sergey_yakovlev:3
CREATE TABLE ads
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255),
    description VARCHAR(255),
    user_id     BIGINT                                  NOT NULL,
    price       INTEGER,
    CONSTRAINT pk_ads PRIMARY KEY (id)
);
-- rollback drop table ads;

-- changeset sergey_yakovlev:4
ALTER TABLE ads
    ADD CONSTRAINT FK_ADS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id)
        ON DELETE CASCADE;
-- rollback alter table ads drop constraint FK_ADS_ON_USER;

-- changeset sergey_yakovlev:5
CREATE TABLE comment
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text       VARCHAR(255),
    user_id    BIGINT                                  NOT NULL,
    ads_id     BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_comment PRIMARY KEY (id)
);
-- rollback drop table comment;

-- changeset sergey_yakovlev:6
ALTER TABLE comment
    ADD CONSTRAINT FK_COMMENT_ON_ADS FOREIGN KEY (ads_id) REFERENCES ads (id)
        ON DELETE CASCADE;
-- rollback alter table comment drop constraint FK_COMMENT_ON_ADS;

-- changeset sergey_yakovlev:7
ALTER TABLE comment
    ADD CONSTRAINT FK_COMMENT_ON_USER FOREIGN KEY (user_id) REFERENCES users (id)
        ON DELETE CASCADE;
-- rollback alter table comment drop constraint FK_COMMENT_ON_USER;

-- changeset sergey_yakovlev:8
CREATE TABLE avatar
(
    user_id    BIGINT NOT NULL,
    media_type VARCHAR(255),
    data       BYTEA,
    CONSTRAINT pk_avatar PRIMARY KEY (user_id)
);
-- rollback drop table avatar;

-- changeset sergey_yakovlev:9
ALTER TABLE avatar
    ADD CONSTRAINT FK_AVATAR_ON_USER FOREIGN KEY (user_id) REFERENCES users (id)
        ON DELETE CASCADE;
-- rollback alter table avatar drop constraint FK_AVATAR_ON_USER;

-- changeset sergey_yakovlev:10
CREATE TABLE ads_image
(
    ads_id     BIGINT NOT NULL,
    media_type VARCHAR(255),
    data       BYTEA,
    CONSTRAINT pk_ads_image PRIMARY KEY (ads_id)
);
-- rollback drop table ads_image;

-- changeset sergey_yakovlev:11
ALTER TABLE ads_image
    ADD CONSTRAINT FK_ADS_IMAGE_ON_ADS FOREIGN KEY (ads_id) REFERENCES ads (id)
        ON DELETE CASCADE;
-- rollback alter table ads_image drop constraint FK_ADS_IMAGE_ON_ADS;

-- changeset atrilos:1
ALTER TABLE ads_image
    DROP COLUMN data;
-- rollback ALTER TABLE ads_image ADD COLUMN data bytea;

-- changeset atrilos:2
ALTER TABLE avatar
    DROP COLUMN data;
-- rollback ALTER TABLE avatar ADD COLUMN data bytea;

-- changeset atrilos:3
ALTER TABLE ads_image
    ADD COLUMN data oid;
-- rollback ALTER TABLE ads_image DROP COLUMN data;

-- changeset atrilos:4
ALTER TABLE avatar
    ADD COLUMN data oid;
-- rollback ALTER TABLE avatar DROP COLUMN data;
