-- liquibase formatted sql

-- changeset sergey_yakovlev:1
CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    email      VARCHAR(255)                            NOT NULL UNIQUE,
    password   VARCHAR(255),
    phone      VARCHAR(255),
    image      VARCHAR,
    role       VARCHAR(255)                            NOT NULL
);

CREATE TABLE comment
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text       VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE avatar
(
    id BIGINT,
    media_type VARCHAR(255),
    data VARCHAR(255)
);

CREATE TABLE AdsImage
(
    id BIGINT,
    media_type VARCHAR(255),
    data VARCHAR(255)
);

CREATE TABLE ads
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(255),
    description VARCHAR(255),
    price INTEGER
);